// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtj6lOGhdZ1uzYmDnQIfRrP-b19NsV_gg',
    appId: '1:302120084179:web:c973abab4b7376dab62a26',
    messagingSenderId: '302120084179',
    projectId: 'supplink-c4792',
    authDomain: 'supplink-c4792.firebaseapp.com',
    databaseURL: 'https://supplink-c4792-default-rtdb.firebaseio.com',
    storageBucket: 'supplink-c4792.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ2091UKlvMB2g4lIBJJQl-AlJJrBtSBQ',
    appId: '1:302120084179:android:f16fb964eb78defab62a26',
    messagingSenderId: '302120084179',
    projectId: 'supplink-c4792',
    databaseURL: 'https://supplink-c4792-default-rtdb.firebaseio.com',
    storageBucket: 'supplink-c4792.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsmC5eGmuooKYP_KYpoeZS1VBhvVxTHqo',
    appId: '1:302120084179:ios:a6b798026719afefb62a26',
    messagingSenderId: '302120084179',
    projectId: 'supplink-c4792',
    databaseURL: 'https://supplink-c4792-default-rtdb.firebaseio.com',
    storageBucket: 'supplink-c4792.appspot.com',
    iosBundleId: 'com.example.suppllink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsmC5eGmuooKYP_KYpoeZS1VBhvVxTHqo',
    appId: '1:302120084179:ios:64477c08eb1cceeeb62a26',
    messagingSenderId: '302120084179',
    projectId: 'supplink-c4792',
    databaseURL: 'https://supplink-c4792-default-rtdb.firebaseio.com',
    storageBucket: 'supplink-c4792.appspot.com',
    iosBundleId: 'com.example.suppllink.RunnerTests',
  );
}
